global using System;
global using System.Collections.Generic;
global using System.Collections.ObjectModel;
global using System.Diagnostics;
global using System.Globalization;
global using System.IO;
global using System.Linq;
global using System.Reflection;
global using System.Text;
global using System.Threading.Tasks;
global using System.Windows;
global using System.Windows.Controls;
global using System.Windows.Data;
global using System.Windows.Media;
global using System.Windows.Media.Imaging;
global using BgCommon.Prism.Wpf;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using ERole = BgCommon.Prism.Wpf.Authority.Entities.Role;
global using Ioc = BgCommon.Prism.Wpf.Ioc;
global using Lang = BgCommon.Localization.LocalizationProviderFactory;
global using ModuleInfo = BgCommon.Prism.Wpf.Authority.Entities.ModuleInfo;