global using System.Collections;
global using System.Collections.Concurrent;
global using System.Collections.ObjectModel;
global using System.ComponentModel;
global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Globalization;
global using System.IO;
global using System.Linq.Expressions;
global using System.Reflection;
global using System.Runtime.InteropServices;
global using System.Runtime.CompilerServices;
global using System.Text;
global using System.Windows;
global using System.Windows.Controls;
global using System.Windows.Controls.Primitives;
global using System.Windows.Data;
global using System.Windows.Input;
global using System.Windows.Markup;
global using System.Windows.Media;
global using System.Windows.Media.Imaging;
global using System.Windows.Threading;
global using BgCommon.Collections;
global using BgCommon.Localization;
global using BgLogger;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Design;
global using Microsoft.EntityFrameworkCore.Storage;
global using Microsoft.Extensions.Localization;
global using Microsoft.Extensions.Logging;
global using Microsoft.WindowsAPICodePack.Dialogs;
global using NLog;
global using ERole = BgCommon.Prism.Wpf.Authority.Entities.Role;
global using Lang = BgCommon.Localization.LocalizationProviderFactory;
global using ModuleInfo = BgCommon.Prism.Wpf.Authority.Entities.ModuleInfo;
global using Regions = Prism.Navigation.Regions;