global using System.Collections;
global using System.Collections.Immutable;
global using System.Collections.ObjectModel;
global using System.ComponentModel;
global using System.Composition;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Globalization;
global using System.IO;
global using System.Net.Http;
global using System.Runtime.InteropServices;
global using System.Text;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using System.Text.RegularExpressions;
global using System.Windows;
global using System.Windows.Controls;
global using System.Windows.Data;
global using System.Windows.Documents;
global using System.Windows.Input;
global using System.Windows.Interop;
global using System.Windows.Media;
global using System.Windows.Threading;
global using System.Xml.Linq;
global using BgCommon.Prism.Wpf;
global using BgCommon.Prism.Wpf.Models;
global using BgCommon.Prism.Wpf.MVVM;
global using BgCommon.Prism.Wpf.Services;
global using BgLogger;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using ICSharpCode.AvalonEdit;
global using ICSharpCode.AvalonEdit.CodeCompletion;
global using ICSharpCode.AvalonEdit.Document;
global using ICSharpCode.AvalonEdit.Editing;
global using ICSharpCode.AvalonEdit.Folding;
global using ICSharpCode.AvalonEdit.Highlighting;
global using ICSharpCode.AvalonEdit.Rendering;
global using ICSharpCode.AvalonEdit.Snippets;
global using TextDocument = ICSharpCode.AvalonEdit.Document.TextDocument;
global using CommonFontWeights = System.Windows.FontWeights;
global using CommonTextEventArgs = System.Windows.Input.TextCompositionEventArgs;
global using CommonBrush = System.Windows.Media.Brush;
global using CommonImage = System.Windows.Media.ImageSource;
global using StyledProperty = System.Windows.DependencyProperty;