using BgControls.Windows.Controls.PropertyGrid;
using System.ComponentModel;
using System.Windows.Input;
using pga = BgControls.Windows.Controls.PropertyGrid.Attributes;

namespace ToolkitDemo.Models;

[pga.ExpandedCategory("Numeric Editors", false)]
[pga.ExpandedCategory("Non-Numeric Editors", false)]
public class AllEditorTypes
{
    public AllEditorTypes()
    {
        this.TestCommand = new RelayCommand(this.OnTest);
    }

    [Category("Non-Numeric Editors")]
    [Description("(C# string type) This property uses a TextBox as the default editor.")]
    [pga.PropertyOrder(1)]
    public string String { get; set; }

    [Category("Non-Numeric Editors")]
    [Description("(C# bool type) This property uses a CheckBox as the default editor.")]
    [pga.PropertyOrder(2)]
    public bool Boolean { get; set; }

    [Category("Numeric Editors")]
    [Description("(C# int type) This property uses an IntegerUpDown as the default editor.")]
    public int Int32 { get; set; }

    [Category("Numeric Editors")]
    [Description("(C# double type) This property uses a DoubleUpDown as the default editor.")]
    public double Double { get; set; }

    [Category("Numeric Editors")]
    [Description("(C# short type) This property uses a ShortUpDown as the default editor.")]
    public short Int16 { get; set; }

    [Category("Numeric Editors")]
    [Description("(C# long type) This property uses a LongUpDown as the default editor.")]
    public long Int64 { get; set; }

    [Category("Numeric Editors")]
    [Description("(C# float type) This property uses a SingleUpDown as the default editor.")]
    public float Single { get; set; }

    [Category("Numeric Editors")]
    [Description("(C# decimal type) This property uses a Decimal as the default editor.")]
    public decimal Decimal { get; set; }

    [Category("Numeric Editors")]
    [Description("(C# byte type) This property uses a ByteUpDown as the default editor.")]
    public byte Byte { get; set; }

    [Category("Numeric Editors")]
    [Description("(C# sbyte type) This property uses a SByteUpDown as the default editor. This is an internal class for CLS compliance reasons. Can only be autogenerated.")]
    public sbyte SByte { get; set; }

    [Category("Numeric Editors")]
    [Description("(C# uint type) This property uses a UInteger as the default editor. This is an internal class for CLS compliance reasons. Can only be autogenerated.")]
    public uint UInt32 { get; set; }

    [Category("Numeric Editors")]
    [Description("(C# ulong type) This property uses a ULongUpDown as the default editor. This is an internal class for CLS compliance reasons. Can only be autogenerated.")]
    public ulong UInt64 { get; set; }

    [Category("Numeric Editors")]
    [Description("(C# ushort type) This property uses a UShortUpDown as the default editor. This is an internal class for CLS compliance reasons. Can only be autogenerated.")]
    public ushort UInt16 { get; set; }

    [Category("Non-Numeric Editors")]
    [Description("This property uses a DateTimeUpDown as the default editor.")]
    [pga.PropertyOrder(0)]
    public System.DateTime DateTime { get; set; }

    [Category("Non-Numeric Editors")]
    [Description("This property uses a TimeSpanUpDown as the default editor.")]
    [pga.PropertyOrder(0)]
    public System.TimeSpan TimeSpan { get; set; }

    [Category("Non-Numeric Editors")]
    [Description("This property uses a ColorPicker as the default editor.")]
    public System.Windows.Media.Color? Color { get; set; }

    [pga.VisibleTo("Numeric Editors", HorizontalAlignment.Center, PropertyGridTarget.Categorized)]
    [pga.VisibleTo(nameof(Int32), HorizontalAlignment.Stretch, PropertyGridTarget.Property)]
    [pga.VisibleTo(nameof(Int64), HorizontalAlignment.Left, PropertyGridTarget.Property)]
    [pga.VisibleTo(nameof(Double), HorizontalAlignment.Left, PropertyGridTarget.Property)]
    [Category("Non-Numeric Editors")]
    [Description("(C# enum type) This property uses a ComboBox as the default editor. The ComboBox is auto-populated with the enum values.")]
    public HorizontalAlignment Enum { get; set; }

    private DemoEnum checkEnum = DemoEnum.Demo;

    [pga.VisibleTo(nameof(Double), DemoEnum.Demo, PropertyGridTarget.Property)]
    [Category("Non-Numeric Editors")]
    [Description("(C# enum type) This property uses a ComboBox as the default editor. The ComboBox is auto-populated with the enum values.")]

    public DemoEnum CheckEnum => this.checkEnum;

    [Category("Non-Numeric Editors")]
    [Description("This property uses a ComboBox as the default editor.")]
    public FontFamily FontFamily { get; set; }

    [Category("Non-Numeric Editors")]
    [Description("This property uses a ComboBox as the default editor.")]
    public FontWeight FontWeight { get; set; }

    [Category("Non-Numeric Editors")]
    [Description("This property uses a ComboBox as the default editor.")]
    public FontStyle FontStyle { get; set; }

    [Category("Non-Numeric Editors")]
    [Description("This property uses a ComboBox as the default editor.")]
    public FontStretch FontStretch { get; set; }

    [Category("Non-Numeric Editors")]
    [Description("This property uses a Guid as the default editor.")]
    public Guid Guid { get; set; }

    [Category("Non-Numeric Editors")]
    [Description("This property uses a Char as the default editor.")]
    public Char Char { get; set; }

    [Category("Non-Numeric Editors")]
    [PasswordPropertyText(true)]
    public string Password { get; set; }

    [Category("Non-Numeric Editors")]
    [Description("This property uses a FilePicker as the default editor.")]
    public FileInfo File { get; set; }

    [Category("Non-Numeric Editors")]
    [Description("This property uses a PrimitiveTypeCollectionEditor as the default editor.")]
    public List<string> ListOfStrings { get; set; }

    [Category("Non-Numeric Editors")]
    [Description("This property uses a PrimitiveTypeCollectionEditor as the default editor.")]
    public List<int> ListOfInt32 { get; set; }

    [Category("Non-Numeric Editors")]
    [Description("(C# IList<T> type) This property uses a CollectionEditor as the default editor.")]
    public List<Person> ListOfPerson { get; set; }

    [Category("Non-Numeric Editors")]
    [Description("(C# IDictionary<T> type) This property uses a CollectionEditor as the default editor.")]
    public Dictionary<int, System.Windows.Media.Color> Dictionary { get; set; }

    [Category("Non-Numeric Editors")]
    [Description("(C# ICollection<T> type) This property uses a CollectionEditor as the default editor.")]
    public Collection<Person> CollectionOfPerson { get; set; }

    [pga.ExpandableObject]
    [Category("Non-Numeric Editors")]
    [Description("This property is a complex property and has no default editor.")]
    public Person Person { get; set; }

    [Category("Non-Numeric Editors")]
    [Description("This property is a complex property and has no default editor.")]
    public Person PersonCombo { get; set; }

    [pga.ExpandableObject]
    [pga.Position("PickUpCommand", "LocateCommand", PickUpSource = pga.CommandSource.ViewModel, LocateSource = pga.CommandSource.ViewModel)]
    [Category("Non-Numeric Editors")]
    [Description("This property is a complex property and has no default editor.")]
    public Position Position { get; set; }

    [DisplayName("Test Command")]
    [Category("Non-Numeric Editors")]
    [Description("This property is a complex property and has no default editor.")]
    public ICommand TestCommand { get; set; }

    private void OnTest()
    {
        Debug.WriteLine("Test Command has executed!");
    }

    private static AllEditorTypes? instance;
    private static AllEditorTypes? instance2;

    public static AllEditorTypes Instance
    {
        get
        {
            if (instance == null)
            {
                instance = CreateInstance();
            }

            return instance;
        }
    }

    public static AllEditorTypes Instance2
    {
        get
        {
            if (instance2 == null)
            {
                instance2 = CreateInstance();
            }

            return instance2;
        }
    }

    private static WeakReference<AllEditorTypes> instance3 = new WeakReference<AllEditorTypes>(null);

    public static AllEditorTypes Instance3
    {
        get
        {
            if (!instance3.TryGetTarget(out var target) || target == null)
            {
                target = CreateInstance();
                instance3.SetTarget(target);
            }

            return target;
        }
    }

    private static AllEditorTypes CreateInstance()
    {
        var instance = new AllEditorTypes();
        instance.Boolean = true;
        instance.Byte = (byte)1;
        instance.Color = Colors.Blue;
        instance.DateTime = System.DateTime.Now;
        instance.Decimal = 2;
        instance.Double = 3.0d;
        instance.Enum = HorizontalAlignment.Center;
        instance.FontFamily = new FontFamily("Arial");
        instance.FontStretch = FontStretches.Normal;
        instance.FontStyle = FontStyles.Italic;
        instance.FontWeight = FontWeights.Bold;
        instance.Guid = new Guid("F9168C5E-CEB2-4faa-B6BF-329BF39FA1E4");
        instance.Char = 'T';
        instance.Password = "This is my password";
        instance.Int16 = (short)4;
        instance.Int32 = (int)5;
        instance.Int64 = 6L;
        instance.ListOfInt32 = new List<int>() { 1, 2, 3 };
        instance.ListOfPerson = new List<Person>() { new Person() { Name = "John Smith" }, new Person() { Name = "Robert King" } };
        instance.ListOfStrings = new List<string>() { "string1", "string2", "string3" };
        instance.Dictionary = new Dictionary<int, System.Windows.Media.Color>() { { 22, System.Windows.Media.Color.FromRgb(255, 0, 0) }, { 33, System.Windows.Media.Color.FromRgb(0, 255, 0) } };
        instance.CollectionOfPerson = new Collection<Person>() { new Person() { Name = "Tom McNeil" }, new Person() { Name = "Mike Campbell" } };
        instance.Person = new Person() { Name = "John Smith" };
        instance.SByte = (sbyte)7;
        instance.Single = 8f;
        instance.String = "this is a string";
        instance.TimeSpan = System.TimeSpan.FromHours(2);
        instance.UInt16 = (ushort)9;
        instance.UInt32 = (uint)10;
        instance.UInt64 = (ulong)11;
        instance.File = new FileInfo("c:\\MyFile.txt");
        instance.Person = new Person() { Name = "John Smith" };
        instance.PersonCombo = instance.ListOfPerson[0];
        instance.Position = new Position();
        return instance;
    }
}

[Flags]
public enum DemoEnum
{
    Test,

    Demo,
}
