//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BgCommon.Localization;

/// <summary>
/// Provides strongly-typed access to all localizable strings.
/// </summary>
public partial class LocalizationProxy
{
    /// <summary>
    ///   关于
    /// </summary>
    public static string About
    {
        get => LocalizationProviderFactory.GetString(nameof(About));
    }


    /// <summary>
    ///   基础设置
    /// </summary>
    public static string BaseSetting
    {
        get => LocalizationProviderFactory.GetString(nameof(BaseSetting));
    }


    /// <summary>
    ///   板高
    /// </summary>
    public static string BoardHeight
    {
        get => LocalizationProviderFactory.GetString(nameof(BoardHeight));
    }


    /// <summary>
    ///   板宽
    /// </summary>
    public static string BoardWidth
    {
        get => LocalizationProviderFactory.GetString(nameof(BoardWidth));
    }


    /// <summary>
    ///   取消
    /// </summary>
    public static string Cancel
    {
        get => LocalizationProviderFactory.GetString(nameof(Cancel));
    }


    /// <summary>
    ///   清除报警
    /// </summary>
    public static string ClearAlarm
    {
        get => LocalizationProviderFactory.GetString(nameof(ClearAlarm));
    }


    /// <summary>
    ///   关闭
    /// </summary>
    public static string Close
    {
        get => LocalizationProviderFactory.GetString(nameof(Close));
    }


    /// <summary>
    ///   确定
    /// </summary>
    public static string Confirm
    {
        get => LocalizationProviderFactory.GetString(nameof(Confirm));
    }


    /// <summary>
    ///   连接
    /// </summary>
    public static string Connect
    {
        get => LocalizationProviderFactory.GetString(nameof(Connect));
    }


    /// <summary>
    ///   复制到剪贴板
    /// </summary>
    public static string CopyToClipboard
    {
        get => LocalizationProviderFactory.GetString(nameof(CopyToClipboard));
    }


    /// <summary>
    ///   封面图像
    /// </summary>
    public static string CoverImage
    {
        get => LocalizationProviderFactory.GetString(nameof(CoverImage));
    }


    /// <summary>
    ///   创建时间
    /// </summary>
    public static string CreateTime
    {
        get => LocalizationProviderFactory.GetString(nameof(CreateTime));
    }


    /// <summary>
    ///   删除
    /// </summary>
    public static string Delete
    {
        get => LocalizationProviderFactory.GetString(nameof(Delete));
    }


    /// <summary>
    ///   删除所有
    /// </summary>
    public static string DeleteAll
    {
        get => LocalizationProviderFactory.GetString(nameof(DeleteAll));
    }


    /// <summary>
    ///   断开连接
    /// </summary>
    public static string DisConnect
    {
        get => LocalizationProviderFactory.GetString(nameof(DisConnect));
    }


    /// <summary>
    ///   显示
    /// </summary>
    public static string Display
    {
        get => LocalizationProviderFactory.GetString(nameof(Display));
    }


    /// <summary>
    ///   完成
    /// </summary>
    public static string Done
    {
        get => LocalizationProviderFactory.GetString(nameof(Done));
    }


    /// <summary>
    ///   English (en-US)
    /// </summary>
    public static string en_US
    {
        get => LocalizationProviderFactory.GetString(nameof(en_US));
    }


    /// <summary>
    ///   English (en-US)
    /// </summary>
    public static string en_US_Remark
    {
        get => LocalizationProviderFactory.GetString(nameof(en_US_Remark));
    }


    /// <summary>
    ///   错误提示
    /// </summary>
    public static string ErrorPrompt
    {
        get => LocalizationProviderFactory.GetString(nameof(ErrorPrompt));
    }


    /// <summary>
    ///   运行
    /// </summary>
    public static string Execute
    {
        get => LocalizationProviderFactory.GetString(nameof(Execute));
    }


    /// <summary>
    ///   路径
    /// </summary>
    public static string FilePath
    {
        get => LocalizationProviderFactory.GetString(nameof(FilePath));
    }


    /// <summary>
    ///   文件大小
    /// </summary>
    public static string FileSize
    {
        get => LocalizationProviderFactory.GetString(nameof(FileSize));
    }


    /// <summary>
    ///   全屏
    /// </summary>
    public static string FullScreen
    {
        get => LocalizationProviderFactory.GetString(nameof(FullScreen));
    }


    /// <summary>
    ///   通用
    /// </summary>
    public static string General
    {
        get => LocalizationProviderFactory.GetString(nameof(General));
    }


    /// <summary>
    ///   主页
    /// </summary>
    public static string Home
    {
        get => LocalizationProviderFactory.GetString(nameof(Home));
    }


    /// <summary>
    ///   导入
    /// </summary>
    public static string Import
    {
        get => LocalizationProviderFactory.GetString(nameof(Import));
    }


    /// <summary>
    ///   序号
    /// </summary>
    public static string Index
    {
        get => LocalizationProviderFactory.GetString(nameof(Index));
    }


    /// <summary>
    ///   输入
    /// </summary>
    public static string Input
    {
        get => LocalizationProviderFactory.GetString(nameof(Input));
    }


    /// <summary>
    ///   语言
    /// </summary>
    public static string Language
    {
        get => LocalizationProviderFactory.GetString(nameof(Language));
    }


    /// <summary>
    ///   限制Z
    /// </summary>
    public static string LimitZ
    {
        get => LocalizationProviderFactory.GetString(nameof(LimitZ));
    }


    /// <summary>
    ///   本地
    /// </summary>
    public static string Local
    {
        get => LocalizationProviderFactory.GetString(nameof(Local));
    }


    /// <summary>
    ///   登陆
    /// </summary>
    public static string Login
    {
        get => LocalizationProviderFactory.GetString(nameof(Login));
    }


    /// <summary>
    ///   用户名或密码不正确，登陆失败！
    /// </summary>
    public static string LoginFailed
    {
        get => LocalizationProviderFactory.GetString(nameof(LoginFailed));
    }


    /// <summary>
    ///   机器
    /// </summary>
    public static string Machine
    {
        get => LocalizationProviderFactory.GetString(nameof(Machine));
    }


    /// <summary>
    ///   修改
    /// </summary>
    public static string Modify
    {
        get => LocalizationProviderFactory.GetString(nameof(Modify));
    }


    /// <summary>
    ///   修改时间
    /// </summary>
    public static string ModifyTime
    {
        get => LocalizationProviderFactory.GetString(nameof(ModifyTime));
    }


    /// <summary>
    ///   新建
    /// </summary>
    public static string New
    {
        get => LocalizationProviderFactory.GetString(nameof(New));
    }


    /// <summary>
    ///   否
    /// </summary>
    public static string No
    {
        get => LocalizationProviderFactory.GetString(nameof(No));
    }


    /// <summary>
    ///   打开
    /// </summary>
    public static string Open
    {
        get => LocalizationProviderFactory.GetString(nameof(Open));
    }


    /// <summary>
    ///   输出
    /// </summary>
    public static string Output
    {
        get => LocalizationProviderFactory.GetString(nameof(Output));
    }


    /// <summary>
    ///   参数
    /// </summary>
    public static string Parameter
    {
        get => LocalizationProviderFactory.GetString(nameof(Parameter));
    }


    /// <summary>
    ///   密码
    /// </summary>
    public static string Password
    {
        get => LocalizationProviderFactory.GetString(nameof(Password));
    }


    /// <summary>
    ///   暂停
    /// </summary>
    public static string Pause
    {
        get => LocalizationProviderFactory.GetString(nameof(Pause));
    }


    /// <summary>
    ///   项目
    /// </summary>
    public static string Project
    {
        get => LocalizationProviderFactory.GetString(nameof(Project));
    }


    /// <summary>
    ///   项目信息
    /// </summary>
    public static string ProjectInfo
    {
        get => LocalizationProviderFactory.GetString(nameof(ProjectInfo));
    }


    /// <summary>
    ///   项目名称
    /// </summary>
    public static string ProjectName
    {
        get => LocalizationProviderFactory.GetString(nameof(ProjectName));
    }


    /// <summary>
    ///   项目路径
    /// </summary>
    public static string ProjectPath
    {
        get => LocalizationProviderFactory.GetString(nameof(ProjectPath));
    }


    /// <summary>
    ///   保存项目失败，原因：{0}{1}
    /// </summary>
    public static string ProjectSaveError
    {
        get => LocalizationProviderFactory.GetString(nameof(ProjectSaveError));
    }


    /// <summary>
    ///   快速操作
    /// </summary>
    public static string QuickAction
    {
        get => LocalizationProviderFactory.GetString(nameof(QuickAction));
    }


    /// <summary>
    ///   备注
    /// </summary>
    public static string Remark
    {
        get => LocalizationProviderFactory.GetString(nameof(Remark));
    }


    /// <summary>
    ///   复位
    /// </summary>
    public static string Reset
    {
        get => LocalizationProviderFactory.GetString(nameof(Reset));
    }


    /// <summary>
    ///   保存
    /// </summary>
    public static string Save
    {
        get => LocalizationProviderFactory.GetString(nameof(Save));
    }


    /// <summary>
    ///   另存为
    /// </summary>
    public static string SaveAs
    {
        get => LocalizationProviderFactory.GetString(nameof(SaveAs));
    }


    /// <summary>
    ///   设置
    /// </summary>
    public static string Setting
    {
        get => LocalizationProviderFactory.GetString(nameof(Setting));
    }


    /// <summary>
    ///   启动
    /// </summary>
    public static string Start
    {
        get => LocalizationProviderFactory.GetString(nameof(Start));
    }


    /// <summary>
    ///   停止
    /// </summary>
    public static string Stop
    {
        get => LocalizationProviderFactory.GetString(nameof(Stop));
    }


    /// <summary>
    ///   系统提示
    /// </summary>
    public static string SystemPrompt
    {
        get => LocalizationProviderFactory.GetString(nameof(SystemPrompt));
    }


    /// <summary>
    ///   系统警告
    /// </summary>
    public static string SystemWarning
    {
        get => LocalizationProviderFactory.GetString(nameof(SystemWarning));
    }


    /// <summary>
    ///   工具
    /// </summary>
    public static string ToolName
    {
        get => LocalizationProviderFactory.GetString(nameof(ToolName));
    }


    /// <summary>
    ///   夹紧量
    /// </summary>
    public static string TrackClamping
    {
        get => LocalizationProviderFactory.GetString(nameof(TrackClamping));
    }


    /// <summary>
    ///   轨道参数
    /// </summary>
    public static string TrackParameter
    {
        get => LocalizationProviderFactory.GetString(nameof(TrackParameter));
    }


    /// <summary>
    ///   轨道宽度
    /// </summary>
    public static string TrackWidth
    {
        get => LocalizationProviderFactory.GetString(nameof(TrackWidth));
    }


    /// <summary>
    ///   类型 {0} 不是枚举
    /// </summary>
    public static string TypeNotEnum
    {
        get => LocalizationProviderFactory.GetString(nameof(TypeNotEnum));
    }


    /// <summary>
    ///   未命名
    /// </summary>
    public static string Untitled
    {
        get => LocalizationProviderFactory.GetString(nameof(Untitled));
    }


    /// <summary>
    ///   用户登陆
    /// </summary>
    public static string UserLogin
    {
        get => LocalizationProviderFactory.GetString(nameof(UserLogin));
    }


    /// <summary>
    ///   用户名
    /// </summary>
    public static string UserName
    {
        get => LocalizationProviderFactory.GetString(nameof(UserName));
    }


    /// <summary>
    ///   用户名和密码不允许为空！
    /// </summary>
    public static string UserNameOrPasswordIsEmpty
    {
        get => LocalizationProviderFactory.GetString(nameof(UserNameOrPasswordIsEmpty));
    }


    /// <summary>
    ///   Việt Nam
    /// </summary>
    public static string vi
    {
        get => LocalizationProviderFactory.GetString(nameof(vi));
    }


    /// <summary>
    ///   Việt Nam
    /// </summary>
    public static string vi_Remark
    {
        get => LocalizationProviderFactory.GetString(nameof(vi_Remark));
    }


    /// <summary>
    ///   工位
    /// </summary>
    public static string WorkStation
    {
        get => LocalizationProviderFactory.GetString(nameof(WorkStation));
    }


    /// <summary>
    ///   是
    /// </summary>
    public static string Yes
    {
        get => LocalizationProviderFactory.GetString(nameof(Yes));
    }


    /// <summary>
    ///   简体中文(zh-CN)
    /// </summary>
    public static string zh_CN
    {
        get => LocalizationProviderFactory.GetString(nameof(zh_CN));
    }


    /// <summary>
    ///   简体中文(zh-CN)
    /// </summary>
    public static string zh_CN_Remark
    {
        get => LocalizationProviderFactory.GetString(nameof(zh_CN_Remark));
    }


    /// <summary>
    ///   繁體中文（zh-TW）
    /// </summary>
    public static string zh_TW
    {
        get => LocalizationProviderFactory.GetString(nameof(zh_TW));
    }


    /// <summary>
    ///   繁體中文（zh-TW）
    /// </summary>
    public static string zh_TW_Remark
    {
        get => LocalizationProviderFactory.GetString(nameof(zh_TW_Remark));
    }


    /// <summary>
    ///   操作员
    /// </summary>
    public static string 操作员
    {
        get => LocalizationProviderFactory.GetString(nameof(操作员));
    }


    /// <summary>
    ///   工程师
    /// </summary>
    public static string 工程师
    {
        get => LocalizationProviderFactory.GetString(nameof(工程师));
    }


    /// <summary>
    ///   管理员
    /// </summary>
    public static string 管理员
    {
        get => LocalizationProviderFactory.GetString(nameof(管理员));
    }


    /// <summary>
    ///   请输入
    /// </summary>
    public static string 请输入
    {
        get => LocalizationProviderFactory.GetString(nameof(请输入));
    }


    /// <summary>
    ///   最大值
    /// </summary>
    public static string 最大值
    {
        get => LocalizationProviderFactory.GetString(nameof(最大值));
    }


    /// <summary>
    ///   最小值
    /// </summary>
    public static string 最小值
    {
        get => LocalizationProviderFactory.GetString(nameof(最小值));
    }


    // /// <summary>
    // /// This is the auto-generated implementation for the partial method defined in the hand-written file.
    // /// </summary>
    // public partial void OnAllPropertiesChanged()
    // {
    //     OnPropertyChanged(nameof(About));
    //     OnPropertyChanged(nameof(BaseSetting));
    //     OnPropertyChanged(nameof(BoardHeight));
    //     OnPropertyChanged(nameof(BoardWidth));
    //     OnPropertyChanged(nameof(Cancel));
    //     OnPropertyChanged(nameof(ClearAlarm));
    //     OnPropertyChanged(nameof(Close));
    //     OnPropertyChanged(nameof(Confirm));
    //     OnPropertyChanged(nameof(Connect));
    //     OnPropertyChanged(nameof(CopyToClipboard));
    //     OnPropertyChanged(nameof(CoverImage));
    //     OnPropertyChanged(nameof(CreateTime));
    //     OnPropertyChanged(nameof(Delete));
    //     OnPropertyChanged(nameof(DeleteAll));
    //     OnPropertyChanged(nameof(DisConnect));
    //     OnPropertyChanged(nameof(Display));
    //     OnPropertyChanged(nameof(Done));
    //     OnPropertyChanged(nameof(en_US));
    //     OnPropertyChanged(nameof(en_US_Remark));
    //     OnPropertyChanged(nameof(ErrorPrompt));
    //     OnPropertyChanged(nameof(Execute));
    //     OnPropertyChanged(nameof(FilePath));
    //     OnPropertyChanged(nameof(FileSize));
    //     OnPropertyChanged(nameof(FullScreen));
    //     OnPropertyChanged(nameof(General));
    //     OnPropertyChanged(nameof(Home));
    //     OnPropertyChanged(nameof(Import));
    //     OnPropertyChanged(nameof(Index));
    //     OnPropertyChanged(nameof(Input));
    //     OnPropertyChanged(nameof(Language));
    //     OnPropertyChanged(nameof(LimitZ));
    //     OnPropertyChanged(nameof(Local));
    //     OnPropertyChanged(nameof(Login));
    //     OnPropertyChanged(nameof(LoginFailed));
    //     OnPropertyChanged(nameof(Machine));
    //     OnPropertyChanged(nameof(Modify));
    //     OnPropertyChanged(nameof(ModifyTime));
    //     OnPropertyChanged(nameof(New));
    //     OnPropertyChanged(nameof(No));
    //     OnPropertyChanged(nameof(Open));
    //     OnPropertyChanged(nameof(Output));
    //     OnPropertyChanged(nameof(Parameter));
    //     OnPropertyChanged(nameof(Password));
    //     OnPropertyChanged(nameof(Pause));
    //     OnPropertyChanged(nameof(Project));
    //     OnPropertyChanged(nameof(ProjectInfo));
    //     OnPropertyChanged(nameof(ProjectName));
    //     OnPropertyChanged(nameof(ProjectPath));
    //     OnPropertyChanged(nameof(ProjectSaveError));
    //     OnPropertyChanged(nameof(QuickAction));
    //     OnPropertyChanged(nameof(Remark));
    //     OnPropertyChanged(nameof(Reset));
    //     OnPropertyChanged(nameof(Save));
    //     OnPropertyChanged(nameof(SaveAs));
    //     OnPropertyChanged(nameof(Setting));
    //     OnPropertyChanged(nameof(Start));
    //     OnPropertyChanged(nameof(Stop));
    //     OnPropertyChanged(nameof(SystemPrompt));
    //     OnPropertyChanged(nameof(SystemWarning));
    //     OnPropertyChanged(nameof(ToolName));
    //     OnPropertyChanged(nameof(TrackClamping));
    //     OnPropertyChanged(nameof(TrackParameter));
    //     OnPropertyChanged(nameof(TrackWidth));
    //     OnPropertyChanged(nameof(TypeNotEnum));
    //     OnPropertyChanged(nameof(Untitled));
    //     OnPropertyChanged(nameof(UserLogin));
    //     OnPropertyChanged(nameof(UserName));
    //     OnPropertyChanged(nameof(UserNameOrPasswordIsEmpty));
    //     OnPropertyChanged(nameof(vi));
    //     OnPropertyChanged(nameof(vi_Remark));
    //     OnPropertyChanged(nameof(WorkStation));
    //     OnPropertyChanged(nameof(Yes));
    //     OnPropertyChanged(nameof(zh_CN));
    //     OnPropertyChanged(nameof(zh_CN_Remark));
    //     OnPropertyChanged(nameof(zh_TW));
    //     OnPropertyChanged(nameof(zh_TW_Remark));
    //     OnPropertyChanged(nameof(操作员));
    //     OnPropertyChanged(nameof(工程师));
    //     OnPropertyChanged(nameof(管理员));
    //     OnPropertyChanged(nameof(请输入));
    //     OnPropertyChanged(nameof(最大值));
    //     OnPropertyChanged(nameof(最小值));
    // }
}